Add references to issues and PRs in markdown
hacs/frontend pull request #477
Opened 2021-06-09 17:33 UTC by MrBartusek

This PR adds [linkify-issues](https://github.com/sindresorhus/linkify-issues) library

See last change with Spanish translation:

Before:

![image](https://user-images.githubusercontent.com/23432278/121401276-d2732a80-c958-11eb-910c-62647ecb55fa.png)

After:

![image](https://user-images.githubusercontent.com/23432278/121401342-e7e85480-c958-11eb-85ea-bab7297780e0.png)

2021-06-09 19:36 UTC, ludeeus requested changes
This adds another dependency (which again drags in 7 more), that is too much for something that can be handled without a third-party library.

2021-06-12 11:23 UTC, MrBartusek commented
@ludeeus Done!

![image](https://user-images.githubusercontent.com/23432278/121774149-2ceecf80-cb81-11eb-9dac-4b1244c684a0.png)

2021-06-12 11:25 UTC, ludeeus approved these changes
Awesome!

2021-06-12 11:25 UTC, ludeeus commented on src/tools/markdown/markdown.ts
> +        const url = `https://github.com/${fullName}/issues/${issue}`;
```suggestion
        const fullReference = reference.replace(/^#/, `${repo.full_name}#`);
        const [fullName, issue] = fullReference.split('#');
        const url = `https://github.com/${fullName}/issues/${issue}`;
```

2021-06-12 11:43 UTC, merged