Account for longer translation description texts in entry panel
hacs/frontend pull request #579
Opened 2022-04-03 21:05 UTC by spacegaier

Potentially too hacky, but I used `56px` since that is the width of the icon plus its margin on the right.

**Before:**
![image](https://user-images.githubusercontent.com/114137/161448648-c3983717-bc56-47d8-a239-2e492975d0cd.png)

**After:**
![image](https://user-images.githubusercontent.com/114137/161448631-06051a37-9b05-45ee-9dd1-f5f44d6de223.png)

Only tested via browser dev tools.

2022-04-03 21:08 UTC, ludeeus requested changes
Remove the icon instead.

2022-04-03 21:09 UTC, spacegaier commented
TBH, I really like the icon to highlight it is basically a shortcut / navigation to somewhere else.

2022-04-04 05:44 UTC, ludeeus commented
The entry does not navigate and is definitely not a shortcut, it opens a dialog.

2022-04-04 06:44 UTC, spacegaier commented
Yes, but then navigates to the add-ons 😄, but your call reg. the icon.

BTW: Does the auto navigation after 10 seconds in that dialog work for you? Does not work on my end (progress bars goes to 10, but nothing happens). If it is not a known issue, I can raise one here.

2022-04-04 06:45 UTC, ludeeus commented
I know about it, but fixing it is low on my list since no one should actually ever see that dialog at all.

2022-04-04 09:05 UTC, merged